framework:
    messenger:
        default_bus: command.bus
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            sync:
                dsn: "sync://"
        buses:
            command.bus:
                middleware:
                    - validation
                    - 'App\Infrastructure\Middleware\FlushMiddleware'
                    - doctrine_ping_connection
                    - doctrine_transaction
            event.bus:
                middleware:
                    - validation
                    - 'App\Infrastructure\Middleware\FlushMiddleware'
                    - doctrine_ping_connection
                    - doctrine_transaction
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
            query.bus: ~
        routing:
            'App\Infrastructure\Messenger\Command\AsyncCommandInterface': async
            'App\Infrastructure\Messenger\Command\SyncCommandInterface': sync
            'App\Infrastructure\Messenger\Event\PublicEventInterface': async
            'App\Infrastructure\Messenger\Event\PrivateEventInterface': async

when@test:
    framework:
        messenger:
            transports:
                async:
                    dsn: test://
