parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Messenger\Command\CommandBus:
        public: true

    App\Infrastructure\Messenger\Event\EventBus:
        public: true

    App\Infrastructure\Client\Looko2ApiClient:
        arguments:
            $baseUrl: '%env(string:LOOKO2_API_BASE_URL)%'

    App\Domain\Downloader\Looko2Downloader:
        public: true

    _instanceof:
        App\Infrastructure\Messenger\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Infrastructure\Messenger\Event\EventListenerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }