parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Infrastructure\Messenger\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Infrastructure\Messenger\Event\EventListenerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }