name: Build and test

on:
  push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Copy parameters
        run: cp .env.test .env && cp

      - name: Create database
        run: php bin/console doctrine:database:create --if-not-exists

      - name: Migrate database
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Unit tests
        run: ./bin/phpunit -c phpunit.xml --testdox --testsuite unit

      - name: Integration tests
        run: ./bin/phpunit -c phpunit.xml --testdox --testsuite integration